#!/bin/bash

# project.test_env
# ${JOB_NAME} is a Jenkins var


IFS="." read -ra array <<< "${JOB_NAME}"
TEST_ENV=${array[1]}
docker pull firefoxtesteng/autopush-integration-tests:latest
docker run --rm -e TEST_ENV=${TEST_ENV} -e GITHUB_ACCESS_TOKEN=${GITHUB_ACCESS_TOKEN} firefoxtesteng/autopush-integration-tests:latest
